name: sm_core
description: "A simple core library for flutter, providing some common utilities and classes."
version: 0.0.5
homepage: "https://github.com/shay-wong/flutter_sm_core"
repository: "https://github.com/shay-wong/flutter_sm_core"
issue_tracker: "https://github.com/shay-wong/flutter_sm_core/issues"

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.9.3
  sm_logger: ^0.0.10
  sm_models: ^0.0.5
  sm_network: ^0.1.0
  sm_widget: ^0.0.8
  sm_get_plus: ^0.0.3
  get: ^4.6.6
  intl: ^0.19.0
  loading_animation_widget: ^1.2.1
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
